// src/content/services.js
// All service pages — drives the dynamic routing and Service template.
// TODO (CONTENT_TODO): Replace placeholder copy with reviewed, approved content.

export const SERVICES = [
  // ── DIGITAL MARKETING: ORGANIC ────────────────────────────────────────────
  {
    slug: 'digital-marketing/seo-services',
    hub: 'digital-marketing',
    group: 'Organic Growth',
    title: 'SEO Services',
    tagline: 'Increase your organic rankings and drive qualified traffic to your website.',
    hero: {
      h1: 'SEO Services That Deliver Measurable Organic Growth',
      sub: 'We build sustainable search visibility through technical excellence, authoritative content, and strategic link development.',
      cta: ['Get a Free SEO Audit', 'View Case Studies'],
    },
    problem: 'Most businesses invest in paid channels and see traffic disappear the moment budget stops. Organic search, built correctly, compounds over time — but only when strategy, technical execution and content work in concert.',
    solution: 'Our SEO practice combines deep technical auditing, competitor gap analysis, content that earns links, and precise tracking against revenue — not just rankings.',
    process: [
      { step: 1, title: 'Discovery & Audit', body: 'We audit your existing site: crawl health, Core Web Vitals, indexation, backlink profile and content gaps.' },
      { step: 2, title: 'Keyword Strategy', body: 'We map keywords to buyer intent stages, prioritising terms that convert, not just terms that receive volume.' },
      { step: 3, title: 'On-Page Optimisation', body: 'Title tags, headings, schema, internal linking, image optimisation and page experience signals are addressed systematically.' },
      { step: 4, title: 'Content Development', body: 'Our writers produce authoritative, original content that satisfies user intent and earns editorial links.' },
      { step: 5, title: 'Link Acquisition', body: 'We earn coverage on relevant, reputable publications through outreach, digital PR and resource link building.' },
      { step: 6, title: 'Reporting & Iteration', body: 'Monthly rank, traffic and revenue attribution reports. We adjust strategy quarterly based on performance data.' },
    ],
    deliverables: ['Technical SEO audit report', 'Keyword strategy document', 'On-page optimisation across priority pages', 'Monthly content calendar', 'Link acquisition campaign', 'Monthly performance report'],
    faq: [
      { q: 'How long does SEO take to show results?', a: 'Most clients begin to see measurable movement in rankings and organic sessions within three to six months, with compounding returns over 12-18 months.' },
      { q: 'Do you guarantee first-page rankings?', a: 'No reputable agency guarantees specific rankings, as search algorithms change frequently. We guarantee a rigorous, transparent process tied to agreed KPIs.' },
      { q: 'Will you work with our existing content team?', a: 'Yes. We are equally comfortable leading content production or providing strategy, briefs and editorial oversight for your in-house writers.' },
      { q: 'How do you measure success?', a: 'We track organic sessions, keyword position distributions, share of voice, leads and revenue attributed to organic — not rankings in isolation.' },
    ],
    related: ['seo-services/local-seo', 'seo-services/seo-audits', 'ppc-management-services'],
    seo: {
      title: 'SEO Services | Upshoot Media',
      description: 'Data-driven SEO services that grow organic traffic, improve rankings and drive qualified leads. Technical, content and link-building expertise in one place.',
    },
  },
  {
    slug: 'digital-marketing/seo-services/local-seo',
    hub: 'digital-marketing',
    group: 'Organic Growth',
    title: 'Local SEO',
    tagline: 'Win visibility in local searches and Google Maps for your service area.',
    hero: {
      h1: 'Local SEO Services That Put Your Business on the Map',
      sub: 'We help local and multi-location businesses rank in the Google Map Pack and organic results for high-intent, near-me searches.',
      cta: ['Get a Free Local SEO Audit', 'Contact Us'],
    },
    problem: 'Consumers searching for services near them convert at a far higher rate than general search traffic — yet most local businesses remain invisible in the Map Pack and local organic results.',
    solution: 'We optimise every component of your local digital presence: Google Business Profile, citations, on-page localisation, review strategy and local content — producing consistent, verifiable NAP signals across the web.',
    process: [
      { step: 1, title: 'Local Audit', body: 'We evaluate your GBP completeness, citation consistency, review profile, and local keyword rankings.' },
      { step: 2, title: 'GBP Optimisation', body: 'Categories, services, photos, Q&A, posts and attributes are configured to maximise Map Pack eligibility.' },
      { step: 3, title: 'Citation Clean-up', body: 'We correct NAP inconsistencies across Yelp, Apple Maps, Bing Places and 50+ directories.' },
      { step: 4, title: 'Local Content', body: 'Location and service-area pages are created or improved to target geo-modified keyword combinations.' },
      { step: 5, title: 'Review Programme', body: 'We design a scalable process for requesting and responding to reviews that grows your star rating authentically.' },
      { step: 6, title: 'Local Reporting', body: 'We report GBP views, direction requests, calls, local pack rankings and organic impressions monthly.' },
    ],
    deliverables: ['GBP audit and optimisation', 'Citation audit and correction', 'Local keyword strategy', 'Location/service-area page development', 'Review acquisition process document', 'Monthly local ranking report'],
    faq: [
      { q: 'How many locations can you manage?', a: 'We handle single-location businesses through enterprise multi-location programmes with hundreds of GBP profiles.' },
      { q: 'Do you manage Google Business Profile on our behalf?', a: 'Yes. We have GBP manager access on all accounts and handle posts, responses and profile maintenance.' },
      { q: 'What industries do you serve for local SEO?', a: 'Healthcare, legal, dental, real estate, food service, retail and home services are among our most common verticals.' },
      { q: 'Can you help with negative reviews?', a: 'We can advise on professional response strategies. We do not manipulate, remove or fabricate reviews.' },
    ],
    related: ['digital-marketing/seo-services', 'digital-marketing/seo-services/seo-audits'],
    seo: {
      title: 'Local SEO Services | Upshoot Media',
      description: 'Local SEO services that improve your Google Maps visibility, citation consistency and local organic rankings for service-area businesses.',
    },
  },
  {
    slug: 'digital-marketing/seo-services/enterprise-seo',
    hub: 'digital-marketing',
    group: 'Organic Growth',
    title: 'Enterprise SEO',
    tagline: 'Scalable search strategy for large websites and competitive markets.',
    hero: {
      h1: 'Enterprise SEO at the Scale and Pace Your Business Demands',
      sub: 'Structured programmes for large websites, multi-brand portfolios and highly competitive verticals — managed by an experienced, senior team.',
      cta: ['Request an Enterprise Consultation', 'Contact Us'],
    },
    problem: 'Large websites introduce SEO complexity that standard agency programmes are not equipped to handle: JavaScript rendering issues, duplicate content at scale, slow deployment cycles and siloed internal teams.',
    solution: 'We deploy structured enterprise SEO programmes that integrate with engineering, product and content teams, using automation to identify issues at scale and senior counsel to prioritise what moves the needle.',
    process: [
      { step: 1, title: 'Programme Scoping', body: 'We map your website architecture, content volume, CMS, dev cadence and internal stakeholders before defining deliverables.' },
      { step: 2, title: 'Technical Audit at Scale', body: 'Crawl-based auditing, log file analysis and Core Web Vitals benchmarking across all templates and verticals.' },
      { step: 3, title: 'Strategic Roadmap', body: 'A prioritised 12-month roadmap with estimated traffic impact per initiative, tied to development sprint cycles.' },
      { step: 4, title: 'Implementation Support', body: 'We work directly with engineering teams to specify, review and validate SEO changes in staging before release.' },
      { step: 5, title: 'Content at Scale', body: 'Programmatic content strategies for category pages, FAQs and long-tail clusters — with quality governance.' },
      { step: 6, title: 'Executive Reporting', body: 'Quarterly business reviews linking organic performance to revenue, presented to C-suite stakeholders.' },
    ],
    deliverables: ['Enterprise technical audit', 'Keyword and content gap analysis', 'Prioritised SEO roadmap', 'Dev integration and QA support', 'Content strategy and governance framework', 'Quarterly executive report'],
    faq: [
      { q: 'What size of website qualifies as enterprise?', a: 'We define enterprise as websites with more than 10,000 indexable pages, multi-country/language requirements, or internal teams requiring coordination.' },
      { q: 'Do you have experience with JavaScript-heavy sites?', a: 'Yes. We have deep experience diagnosing and resolving rendering and indexation issues on React, Vue and Angular sites.' },
      { q: 'Can you work within our agile development cycle?', a: 'We align deliverables to sprint cadences and provide Jira-ready implementation tickets where required.' },
      { q: 'How do you handle international SEO?', a: 'We manage hreflang implementation, subdomain vs. directory structure decisions and localised content strategies for international programmes.' },
    ],
    related: ['digital-marketing/seo-services', 'digital-marketing/seo-services/seo-audits'],
    seo: {
      title: 'Enterprise SEO Services | Upshoot Media',
      description: 'Enterprise SEO programmes for large websites, multi-location businesses and competitive markets. Technical, content and scalable strategy from a senior team.',
    },
  },
  {
    slug: 'digital-marketing/seo-services/seo-audits',
    hub: 'digital-marketing',
    group: 'Organic Growth',
    title: 'SEO Audits',
    tagline: 'A complete diagnostic of your website\'s search performance and technical health.',
    hero: {
      h1: 'Comprehensive SEO Audits That Surface What Is Holding You Back',
      sub: 'We examine every factor that influences your organic visibility — from crawl health and Core Web Vitals to content quality and backlink risk.',
      cta: ['Order an SEO Audit', 'Contact Us'],
    },
    problem: 'Many businesses invest in ongoing SEO without a clear baseline. Without a thorough audit, effort is often misdirected — fixing symptoms rather than root causes.',
    solution: 'Our SEO audit is a structured, evidence-based review delivered as an actionable report. Every finding is prioritised by impact, and every recommendation includes implementation guidance.',
    process: [
      { step: 1, title: 'Crawl Analysis', body: 'We crawl your site to identify broken links, redirect chains, duplicate content, thin pages and indexation issues.' },
      { step: 2, title: 'Technical Review', body: 'Core Web Vitals, page speed, mobile usability, structured data, canonical tags and robots directives are assessed.' },
      { step: 3, title: 'Content Assessment', body: 'We evaluate content depth, topical coverage, E-E-A-T signals and keyword alignment across key page types.' },
      { step: 4, title: 'Backlink Analysis', body: 'We review your link profile for authority, relevance, toxicity and compare it to competitor benchmarks.' },
      { step: 5, title: 'Competitor Benchmark', body: 'Top three organic competitors are benchmarked to identify share of voice gaps and quick-win opportunities.' },
      { step: 6, title: 'Prioritised Recommendations', body: 'All findings are ranked by estimated impact and implementation effort, with clear owner assignments.' },
    ],
    deliverables: ['Executive summary', 'Full technical audit with screenshots', 'Content quality assessment', 'Backlink and toxicity report', 'Competitor benchmarking', 'Prioritised action plan'],
    faq: [
      { q: 'How long does an audit take?', a: 'Our standard audit is completed within 10 business days. Enterprise audits with large crawl volumes may require 15 business days.' },
      { q: 'Do you provide a one-off audit or ongoing support?', a: 'We offer standalone audits and ongoing managed SEO programmes that begin with an audit.' },
      { q: 'What format is the deliverable?', a: 'A structured PDF/slide report with supporting spreadsheet data, all findings hyperlinked to source evidence.' },
      { q: 'Can you audit an international or multi-language site?', a: 'Yes. International audits include hreflang validation, country-specific SERP analysis and localisation assessment.' },
    ],
    related: ['digital-marketing/seo-services', 'digital-marketing/seo-services/local-seo'],
    seo: {
      title: 'SEO Audit Services | Upshoot Media',
      description: 'Comprehensive SEO audits covering technical health, content quality, backlink profile and competitor benchmarks. Delivered as an actionable prioritised report.',
    },
  },
  {
    slug: 'digital-marketing/ppc-management-services',
    hub: 'digital-marketing',
    group: 'Paid Media',
    title: 'PPC Management Services',
    tagline: 'Paid media campaigns that maximise return on every advertising pound spent.',
    hero: {
      h1: 'PPC Management Services Focused on Revenue, Not Clicks',
      sub: 'We design, build and continuously optimise paid search and social campaigns that generate qualified leads and sales for your business.',
      cta: ['Request a PPC Audit', 'Contact Us'],
    },
    problem: 'Paid media is the fastest route to qualified traffic — and the fastest route to wasted budget. Without rigorous account structure, bid strategy and creative testing, most accounts accumulate inefficiency month over month.',
    solution: 'Our certified PPC team takes full accountability for your ad accounts: strategy, structure, creative, bidding and measurement are all owned and continuously improved by one accountable team.',
    process: [
      { step: 1, title: 'Account Audit', body: 'We audit your existing accounts for structural issues, wasted spend, quality score problems and attribution gaps.' },
      { step: 2, title: 'Strategy & Structure', body: 'Campaigns are restructured around business goals: lead generation, e-commerce, brand awareness or local visibility.' },
      { step: 3, title: 'Creative & Copy', body: 'Ad copy, extensions and landing page recommendations are developed and tested against clear hypotheses.' },
      { step: 4, title: 'Launch & Stabilise', body: 'We launch with conservative budgets, establish baseline metrics and stabilise conversion tracking before scaling.' },
      { step: 5, title: 'Optimisation Cycles', body: 'Bi-weekly optimisation: search term reviews, bid adjustments, negative keyword expansion, audience refinement.' },
      { step: 6, title: 'Reporting & QBRs', body: 'Monthly reports covering spend, impressions, clicks, conversions and CPA. Quarterly business reviews to adjust strategy.' },
    ],
    deliverables: ['Account audit report', 'Campaign strategy document', 'Ad copy and extension library', 'Conversion tracking setup', 'Monthly performance report', 'Quarterly strategy review'],
    faq: [
      { q: 'What is your management fee model?', a: 'We typically charge a flat monthly management fee or a percentage of ad spend, depending on account scale. We will propose the most transparent model for your situation.' },
      { q: 'Do you manage Google Ads, Meta and LinkedIn simultaneously?', a: 'Yes. We manage multi-channel paid programmes and provide unified reporting across platforms.' },
      { q: 'Can you take over an existing account?', a: 'Absolutely. We begin with a full audit of any inherited account before making structural changes.' },
      { q: 'How quickly can we expect results?', a: 'Paid channels can deliver traffic from day one. Optimised performance — lower CPA, higher ROAS — typically stabilises within 60-90 days.' },
    ],
    related: ['digital-marketing/ppc-management-services/google-ads', 'digital-marketing/seo-services'],
    seo: {
      title: 'PPC Management Services | Upshoot Media',
      description: 'Managed PPC services across Google Ads, Meta and LinkedIn. We maximise ROAS through rigorous account structure, creative testing and continuous optimisation.',
    },
  },
  {
    slug: 'digital-marketing/social-media-marketing',
    hub: 'digital-marketing',
    group: 'Online Marketing',
    title: 'Social Media Marketing',
    tagline: 'Build audience, authority and engagement across the platforms that matter to your customers.',
    hero: {
      h1: 'Social Media Marketing That Builds Lasting Brand Authority',
      sub: 'We develop and execute social media strategies that grow your audience, deepen customer relationships and support broader marketing objectives.',
      cta: ['Request a Social Strategy Session', 'Contact Us'],
    },
    problem: 'Many businesses post inconsistently, repurpose the same content across every platform and measure success by follower count alone. The result is activity without meaningful business impact.',
    solution: 'We build platform-specific strategies grounded in audience research, brand voice guidelines and conversion goals. Content is original, on-brand and aligned to a structured publishing calendar.',
    process: [
      { step: 1, title: 'Audience & Platform Audit', body: 'We identify where your target customers spend time and audit your current presence on each platform.' },
      { step: 2, title: 'Strategy Development', body: 'Platform-specific content pillars, voice guidelines, posting cadence and KPIs are defined and agreed.' },
      { step: 3, title: 'Content Production', body: 'Our creative team produces graphics, short-form video, carousels and copy to the agreed calendar.' },
      { step: 4, title: 'Scheduling & Publication', body: 'Content is scheduled at optimal times, and community management is handled by our team.' },
      { step: 5, title: 'Paid Amplification', body: 'High-performing organic content is boosted with targeted paid spend for audience growth and lead generation.' },
      { step: 6, title: 'Analytics & Reporting', body: 'Monthly reports cover reach, engagement, follower growth, link clicks and attributed conversions.' },
    ],
    deliverables: ['Platform audit', 'Social strategy document', 'Brand voice guide', 'Monthly content calendar', 'Content assets (graphics, copy, video)', 'Monthly performance report'],
    faq: [
      { q: 'Which platforms do you manage?', a: 'LinkedIn, Instagram, Facebook, X (Twitter) and TikTok. We prioritise platforms based on where your audience is, not by default.' },
      { q: 'Do you handle community management and replies?', a: 'Yes. Community management — monitoring comments, DMs and mentions — is included in our managed social programmes.' },
      { q: 'Can you produce video content?', a: 'Yes. Our creative team produces short-form reels, stories and motion graphics. Video production for longer formats is also available.' },
      { q: 'How do you measure ROI from social?', a: 'We track reach, engagement, website sessions from social, lead form completions and revenue where conversion tracking allows.' },
    ],
    related: ['digital-marketing/social-media-management', 'digital-marketing/content-marketing'],
    seo: {
      title: 'Social Media Marketing Services | Upshoot Media',
      description: 'Strategic social media marketing that builds audience, authority and leads across LinkedIn, Instagram, Facebook and more.',
    },
  },
  {
    slug: 'digital-marketing/content-marketing',
    hub: 'digital-marketing',
    group: 'Online Marketing',
    title: 'Content Marketing',
    tagline: 'Original content that earns trust, drives search visibility and converts readers into customers.',
    hero: {
      h1: 'Content Marketing That Earns Attention and Drives Qualified Leads',
      sub: 'We produce and distribute original content — articles, guides, case studies and video — that builds your authority and supports every stage of the buyer journey.',
      cta: ['Request a Content Strategy', 'Contact Us'],
    },
    problem: 'Generic, keyword-stuffed content may once have worked. Today, search engines and discerning buyers reward depth, expertise and genuine usefulness — standards that most content production processes do not meet.',
    solution: 'We begin with a structured content audit and strategy, then produce original content that meets E-E-A-T standards: expert authors, accurate information, first-hand perspective and transparent sourcing.',
    process: [
      { step: 1, title: 'Content Audit', body: 'We assess existing content: performance, topical coverage, duplication and quality gaps.' },
      { step: 2, title: 'Topic & Keyword Research', body: 'We identify topics that align search demand with your expertise and commercial objectives.' },
      { step: 3, title: 'Content Strategy', body: 'A documented content strategy covers formats, publishing cadence, distribution channels and measurement.' },
      { step: 4, title: 'Production & Quality Review', body: 'Content is written by subject-matter-aware writers and reviewed by our editorial team for accuracy and quality.' },
      { step: 5, title: 'SEO Integration', body: 'On-page optimisation, internal linking and structured data are applied to every piece before publication.' },
      { step: 6, title: 'Distribution & Promotion', body: 'We promote content through email, social, outreach and internal linking to accelerate traffic and link acquisition.' },
    ],
    deliverables: ['Content audit report', 'Content strategy document', 'Editorial calendar (3 months)', 'Original articles/guides per agreed scope', 'On-page SEO per piece', 'Monthly performance report'],
    faq: [
      { q: 'Do your writers have industry expertise?', a: 'We match writers to verticals and have specialists in technology, healthcare, legal, finance and ecommerce.' },
      { q: 'Who owns the content you produce?', a: 'All content produced is your intellectual property upon final payment.' },
      { q: 'Can you update or repurpose existing content?', a: 'Yes. Content refresh and repurposing (articles to video, long-form to social snippets) are part of our service.' },
      { q: 'How long until content starts ranking?', a: 'New content typically enters index within weeks. Ranking movement for competitive terms takes three to nine months with consistent effort.' },
    ],
    related: ['digital-marketing/seo-services', 'digital-marketing/social-media-marketing'],
    seo: {
      title: 'Content Marketing Services | Upshoot Media',
      description: 'Original content marketing that drives organic traffic, earns links and converts readers — written to E-E-A-T standards by experienced writers.',
    },
  },
]

export default SERVICES
